using DevContext.Core.Utilities;

namespace DevContext.Core.Compression;

/// <summary>Removes boilerplate and designer-generated types (auto-generated, T4, .g.cs, DI extensions).</summary>
public sealed class BoilerplateCompressor : ICompressionStrategy
{
    private static readonly ImmutableArray<string> DesignerIndicators =
    [
        "// <auto-generated>",
        "// <autogenerated",
        "#pragma warning disable",
        "// T4 code-generated",
        ".Designer.cs",
        ".g.cs",
        ".g.i.cs",
    ];

    private static readonly ImmutableArray<string> DiExtensionPatterns =
    [
        "Add",
        "Use",
    ];

    /// <summary>Gets the name of this compression strategy.</summary>
    public string Name => "BoilerplateCompressor";
    /// <summary>Gets the execution order.</summary>
    public int Order => 20;

    public ValueTask<CompressionResult> CompressAsync(DiscoveryModel model, CompressionOptions options, CancellationToken ct)
    {
        var tokensBefore = TokenEstimator.Estimate(model, includeRelations: false, excludeHardExcluded: false);
        var notes = new List<string>();
        var trimmedCount = 0;

        foreach (var type in model.Types.Values)
        {
            if (type.IsPruned || type.IsHardExcluded) continue;

            if (IsDesignerFile(type.FilePath))
            {
                type.IsHardExcluded = true;
                type.ExclusionReason = "designer-generated file";
                model.PrunedTypeIds.Add(type.Id);
                trimmedCount++;
                notes.Add($"Excluded designer-generated type '{type.Id}' from '{Path.GetFileName(type.FilePath)}'");
            }

            if (IsDiExtensionType(type))
            {
                type.IsHardExcluded = true;
                type.ExclusionReason = "DI extension type";
                model.PrunedTypeIds.Add(type.Id);
                trimmedCount++;
                notes.Add($"Excluded DI extension type '{type.Id}'");
            }
        }

        var tokensAfter = TokenEstimator.Estimate(model, includeRelations: false, excludeHardExcluded: false);
        return new ValueTask<CompressionResult>(new CompressionResult(
            Name, tokensBefore, tokensAfter, notes));
    }

    private static bool IsDesignerFile(string filePath)
    {
        var fileName = Path.GetFileName(filePath);
        foreach (var indicator in DesignerIndicators)
        {
            if (fileName.Contains(indicator, StringComparison.OrdinalIgnoreCase))
                return true;
        }

        return false;
    }

    private static bool IsDiExtensionType(TypeDiscovery type)
    {
        if (type.Methods.Length == 0) return false;

        var allStatic = type.Methods.All(m => m.IsStatic);
        if (!allStatic) return false;

        var allExtensionLike = type.Methods.All(m =>
        {
            if (m.Name.Length < 3) return false;
            var prefix = m.Name[..3];
            return DiExtensionPatterns.Any(p => prefix.Equals(p, StringComparison.OrdinalIgnoreCase));
        });

        return allExtensionLike;
    }

}
