namespace DevContext.Core.Graph.EntrySurfaces;

using DevContext.Core.Models;

/// <summary>
/// The single source of truth for every entry surface shape.
/// Adding a new shape = one descriptor here + one extractor + one builder + one detection record.
/// </summary>
public static class EntrySurfaceCatalog
{
    public static readonly ImmutableArray<EntrySurfaceDescriptor> All =
    [
        // ── App entry surfaces (signal-gated) ────────────────────────

        new(SignalKey: ArchitectureSignals.Keys.Controllers,
            Kind:       EntryPointKind.HttpEndpoint,
            RenderLabel:"HTTP",
            Role:       SurfaceRole.AppEntry,
            Packages:   [],
            SdkHints:   [],
            SelfNamePatterns: []),

        // ── App entry surfaces (no signal gate — detected generically) ──

        new(SignalKey: "",
            Kind:       EntryPointKind.MessageConsumer,
            RenderLabel:"Bus",
            Role:       SurfaceRole.AppEntry,
            Packages:   [],
            SdkHints:   [],
            SelfNamePatterns: []),

        new(SignalKey: "",
            Kind:       EntryPointKind.DomainEventHandler,
            RenderLabel:"Domain",
            Role:       SurfaceRole.AppEntry,
            Packages:   [],
            SdkHints:   [],
            SelfNamePatterns: []),

        new(SignalKey: "",
            Kind:       EntryPointKind.HostedService,
            RenderLabel:"Background",
            Role:       SurfaceRole.AppEntry,
            Packages:   [],
            SdkHints:   [],
            SelfNamePatterns: []),

        new(SignalKey: "",
            Kind:       EntryPointKind.ScheduledJob,
            RenderLabel:"Scheduled",
            Role:       SurfaceRole.AppEntry,
            Packages:   [],
            SdkHints:   [],
            SelfNamePatterns: []),

        new(SignalKey: "",
            Kind:       EntryPointKind.PublicApi,
            RenderLabel:"Public API",
            Role:       SurfaceRole.AppEntry,
            Packages:   [],
            SdkHints:   [],
            SelfNamePatterns: []),

        new(SignalKey: ArchitectureSignals.Keys.MinimalApis,
            Kind:       EntryPointKind.HttpEndpoint,
            RenderLabel:"HTTP",
            Role:       SurfaceRole.AppEntry,
            Packages:   ["Microsoft.AspNetCore.OpenApi"],
            SdkHints:   ["Microsoft.NET.Sdk.Web"],
            SelfNamePatterns: []),

        new(SignalKey: ArchitectureSignals.Keys.FastEndpoints,
            Kind:       EntryPointKind.HttpEndpoint,
            RenderLabel:"HTTP",
            Role:       SurfaceRole.AppEntry,
            Packages:   ["FastEndpoints"],
            SdkHints:   [],
            SelfNamePatterns: []),

        new(SignalKey: ArchitectureSignals.Keys.Blazor,
            Kind:       EntryPointKind.BlazorPage,
            RenderLabel:"Blazor",
            Role:       SurfaceRole.AppEntry,
            Packages:   ["Microsoft.AspNetCore.Components"],
            SdkHints:   [],
            SelfNamePatterns: []),

        new(SignalKey: ArchitectureSignals.Keys.Grpc,
            Kind:       EntryPointKind.GrpcService,
            RenderLabel:"gRPC",
            Role:       SurfaceRole.AppEntry,
            Packages:   ["Grpc.AspNetCore"],
            SdkHints:   [],
            SelfNamePatterns: ["Grpc"]),

        new(SignalKey: ArchitectureSignals.Keys.SignalR,
            Kind:       EntryPointKind.SignalRHub,
            RenderLabel:"SignalR",
            Role:       SurfaceRole.AppEntry,
            Packages:   ["Microsoft.AspNetCore.SignalR"],
            SdkHints:   [],
            SelfNamePatterns: ["Microsoft.AspNetCore.SignalR"]),

        new(SignalKey: ArchitectureSignals.Keys.Functions,
            Kind:       EntryPointKind.FunctionEntry,
            RenderLabel:"Functions",
            Role:       SurfaceRole.AppEntry,
            Packages:   ["Microsoft.Azure.Functions.Worker"],
            SdkHints:   ["Microsoft.NET.Sdk.Functions"],
            SelfNamePatterns: ["Azure.Functions"]),

        new(SignalKey: ArchitectureSignals.Keys.DesktopUi,
            Kind:       EntryPointKind.UiEntry,
            RenderLabel:"UI",
            Role:       SurfaceRole.AppEntry,
            Packages:   ["Microsoft.WindowsAppSDK", "CommunityToolkit.WinUI", "CommunityToolkit.Mvvm"],
            SdkHints:   ["Microsoft.NET.Sdk.WindowsDesktop"],
            SelfNamePatterns: []),

        // ── Framework-library signals (self-source means the repo IS the framework) ──

        new(SignalKey: ArchitectureSignals.Keys.MassTransit,
            Kind:       EntryPointKind.MessageConsumer,
            RenderLabel:"Bus",
            Role:       SurfaceRole.FrameworkLibrary,
            Packages:   ["MassTransit"],
            SdkHints:   [],
            SelfNamePatterns: ["MassTransit"]),

        new(SignalKey: ArchitectureSignals.Keys.Orleans,
            Kind:       null,
            RenderLabel:"",
            Role:       SurfaceRole.FrameworkLibrary,
            Packages:   [],
            SdkHints:   [],
            SelfNamePatterns: ["Orleans", "Microsoft.Orleans"]),

        new(SignalKey: ArchitectureSignals.Keys.GraphQL,
            Kind:       null,
            RenderLabel:"",
            Role:       SurfaceRole.FrameworkLibrary,
            Packages:   [],
            SdkHints:   [],
            SelfNamePatterns: ["HotChocolate", "GreenDonut"]),

        new(SignalKey: ArchitectureSignals.Keys.Quartz,
            Kind:       null,
            RenderLabel:"",
            Role:       SurfaceRole.FrameworkLibrary,
            Packages:   ["Quartz"],
            SdkHints:   [],
            SelfNamePatterns: []),

        new(SignalKey: ArchitectureSignals.Keys.Hangfire,
            Kind:       null,
            RenderLabel:"",
            Role:       SurfaceRole.FrameworkLibrary,
            Packages:   ["Hangfire"],
            SdkHints:   [],
            SelfNamePatterns: []),

        new(SignalKey: ArchitectureSignals.Keys.Testing,
            Kind:       null,
            RenderLabel:"",
            Role:       SurfaceRole.FrameworkLibrary,
            Packages:   [],
            SdkHints:   [],
            SelfNamePatterns: ["xunit", "nunit"]),

        new(SignalKey: ArchitectureSignals.Keys.EfCore,
            Kind:       null,
            RenderLabel:"",
            Role:       SurfaceRole.FrameworkLibrary,
            Packages:   [
                "Microsoft.EntityFrameworkCore",
                "Microsoft.EntityFrameworkCore.SqlServer",
                "Microsoft.EntityFrameworkCore.Sqlite",
                "Microsoft.EntityFrameworkCore.InMemory",
                "Npgsql.EntityFrameworkCore.PostgreSQL",
                "Pomelo.EntityFrameworkCore.MySql",
            ],
            SdkHints:   [],
            SelfNamePatterns: []),

        new(SignalKey: ArchitectureSignals.Keys.Dapper,
            Kind:       null,
            RenderLabel:"",
            Role:       SurfaceRole.FrameworkLibrary,
            Packages:   ["Dapper"],
            SdkHints:   [],
            SelfNamePatterns: []),

        new(SignalKey: ArchitectureSignals.Keys.FluentValidation,
            Kind:       null,
            RenderLabel:"",
            Role:       SurfaceRole.FrameworkLibrary,
            Packages:   ["FluentValidation"],
            SdkHints:   [],
            SelfNamePatterns: []),

        new(SignalKey: ArchitectureSignals.Keys.AutoMapper,
            Kind:       null,
            RenderLabel:"",
            Role:       SurfaceRole.FrameworkLibrary,
            Packages:   ["AutoMapper"],
            SdkHints:   [],
            SelfNamePatterns: []),

        new(SignalKey: ArchitectureSignals.Keys.MediatR,
            Kind:       null,
            RenderLabel:"",
            Role:       SurfaceRole.FrameworkLibrary,
            Packages:   ["MediatR", "Mediator"],
            SdkHints:   [],
            SelfNamePatterns: []),

        new(SignalKey: ArchitectureSignals.Keys.Serilog,
            Kind:       null,
            RenderLabel:"",
            Role:       SurfaceRole.FrameworkLibrary,
            Packages:   ["Serilog"],
            SdkHints:   [],
            SelfNamePatterns: []),

        new(SignalKey: ArchitectureSignals.Keys.Polly,
            Kind:       null,
            RenderLabel:"",
            Role:       SurfaceRole.FrameworkLibrary,
            Packages:   ["Polly"],
            SdkHints:   [],
            SelfNamePatterns: []),

        new(SignalKey: ArchitectureSignals.Keys.Swagger,
            Kind:       null,
            RenderLabel:"",
            Role:       SurfaceRole.FrameworkLibrary,
            Packages:   ["Swashbuckle.AspNetCore"],
            SdkHints:   [],
            SelfNamePatterns: []),

        new(SignalKey: ArchitectureSignals.Keys.Identity,
            Kind:       null,
            RenderLabel:"",
            Role:       SurfaceRole.FrameworkLibrary,
            Packages:   ["Microsoft.AspNetCore.Identity"],
            SdkHints:   [],
            SelfNamePatterns: []),

        new(SignalKey: ArchitectureSignals.Keys.NLog,
            Kind:       null,
            RenderLabel:"",
            Role:       SurfaceRole.FrameworkLibrary,
            Packages:   ["NLog"],
            SdkHints:   [],
            SelfNamePatterns: []),

        new(SignalKey: ArchitectureSignals.Keys.Redis,
            Kind:       null,
            RenderLabel:"",
            Role:       SurfaceRole.FrameworkLibrary,
            Packages:   ["StackExchange.Redis"],
            SdkHints:   [],
            SelfNamePatterns: []),

        new(SignalKey: ArchitectureSignals.Keys.HealthChecks,
            Kind:       null,
            RenderLabel:"",
            Role:       SurfaceRole.FrameworkLibrary,
            Packages:   ["AspNetCore.HealthChecks"],
            SdkHints:   [],
            SelfNamePatterns: []),

        new(SignalKey: ArchitectureSignals.Keys.Aspire,
            Kind:       null,
            RenderLabel:"",
            Role:       SurfaceRole.FrameworkLibrary,
            Packages:   ["Aspire.Hosting"],
            SdkHints:   [],
            SelfNamePatterns: []),

        new(SignalKey: ArchitectureSignals.Keys.Scrutor,
            Kind:       null,
            RenderLabel:"",
            Role:       SurfaceRole.FrameworkLibrary,
            Packages:   ["Scrutor"],
            SdkHints:   [],
            SelfNamePatterns: []),

        new(SignalKey: ArchitectureSignals.Keys.Refit,
            Kind:       null,
            RenderLabel:"",
            Role:       SurfaceRole.FrameworkLibrary,
            Packages:   ["Refit"],
            SdkHints:   [],
            SelfNamePatterns: []),

        // ── Gateway ─────────────────────────────────────────────────

        new(SignalKey: ArchitectureSignals.Keys.Gateway,
            Kind:       null,
            RenderLabel:"",
            Role:       SurfaceRole.Gateway,
            Packages:   ["Ocelot", "Microsoft.ReverseProxy"],
            SdkHints:   [],
            SelfNamePatterns: ["Yarp", "ReverseProxy"]),
    ];
}
