import { describe, expect, it } from 'vitest';

import { packPreviewHtml } from './pack-preview';

describe('pack preview renderer (D4.5 L4)', () => {
  it('escapes HTML in every format — pack content can contain generics', () => {
    expect(packPreviewHtml('List<Order> & Task<T>', 'plain')).toBe('List&lt;Order&gt; &amp; Task&lt;T&gt;');
    expect(packPreviewHtml('{"a":"<b>"}', 'json')).toBe('{"a":"&lt;b&gt;"}');
    expect(packPreviewHtml('IHandler<T>', 'markdown')).toContain('IHandler&lt;T&gt;');
  });

  it('markdown headings and meta lines get emphasis classes', () => {
    const html = packPreviewHtml('# Context: POST /orders\n_generated by DevContext_\nbody', 'markdown');
    expect(html).toContain('<span class="pv-h"># Context: POST /orders</span>');
    expect(html).toContain('<span class="pv-meta">_generated by DevContext_</span>');
    expect(html).toContain('\nbody');
  });

  it('csharp fences are Prism-highlighted; other fences stay escaped verbatim', () => {
    const md = '```csharp\npublic class Order { }\n```\n```json\n{"x":1}\n```';
    const html = packPreviewHtml(md, 'markdown');
    expect(html).toContain('token'); // Prism emitted token spans for the C# block
    expect(html).toContain('{"x":1}'); // json fence: plain escaped content, no parsing
    expect(html).not.toContain('<script');
  });

  it('an unclosed fence renders its collected lines instead of swallowing them', () => {
    const html = packPreviewHtml('```csharp\nvar x = 1;', 'markdown');
    expect(html).toContain('var');
    expect(html).toContain('pv-meta');
  });

  it('plain/json are verbatim — no heading/fence decoration', () => {
    const html = packPreviewHtml('# not a heading\n```cs\ncode\n```', 'plain');
    expect(html).not.toContain('pv-h');
    expect(html).not.toContain('token');
  });
});
